from lab import *
from datetime import datetime
from zoneinfo import ZoneInfo
def read(name):return json.loads((H/name).read_text())
t,pv,reg,native,topo,repo=map(read,['test-results.json','pv-results.json','regression-results.json','native-results.json','topology.json','repository-evidence.json'])
assert all(t[k]==t[k.replace('_pass','_total')] for k in ['admission_pass','reasoner_pass','query_pass'])
assert pv['pass']==pv['total'] and reg['pass']==reg['total']
assert native['guarded_roundtrip_canonical_equal'] and native['refusal_pass']==native['refusal_total']
assert topo['new_experiment']['isolates']==[]
assert hashlib.sha256((OLD/'ontouml-experimental.json').read_bytes()).hexdigest()=='fef3295149278bdf5a9c446f9699582a565d26fa2f52f76d90f593ba00e20989'
sources=[
 {'id':'GDP','url':'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52013XC1123(01)','locator':'2013/C 343/01, sections 4.2, 5.2, 7 and 9','support':'Product/actor/location traceability in operations; outsourced work has defined responsibilities and written contractual evidence. This does not make every contract a strategic partnership.','limit':'Source-informed design, not a complete GDP compliance model.'},
 {'id':'WHO-STOCKOUT','url':'https://cdn.who.int/media/docs/default-source/medicines/meeting_report_october_shortages.pdf','locator':'Technical definitions meeting report, draft framework, printed p.10','support':'A local stockout description needs medicine and service-delivery context.','limit':'Draft framework with heterogeneous definitions; not asserted to be a universal current normative definition. Time, demand and substitution remain outside the two-edge prototype.'},
 {'id':'EMA-PRAC','url':read('source-manifest.json')['url'],'locator':'EMA/PRAC/183502/2026 pp.3,5,6','support':'Three distinct source recommendations are represented without causal or execution inference.','limit':'Manual documentary extraction, not patient-level evidence.'},
 {'id':'EMA-CURRENT','url':'https://www.ema.europa.eu/en/human-regulatory-overview/post-authorisation/pharmacovigilance-post-authorisation/signal-management','locator':'Monitoring EudraVigilance: legal basis and guidance','support':'The page identifies changes under Regulation 2025/1466 and termination of the former MAH pilot.','limit':'Earlier GVP IX remains useful for conceptual distinctions, but is not used alone as proof of current operational obligations.'},
 {'id':'ICH-Q9','url':'https://www.ema.europa.eu/en/scientific-guidelines/ich-q9-quality-risk-management','locator':'current Q9(R1) page','support':'Pharmaceutical quality risk management grounds the retained bounded RM mission.','limit':'Not every enterprise risk and not a prescribed class diagram.'},
 {'id':'PROJECT-DEFINITION','path':'../2.1.0-alpha.1-g3-3-f-review-handoff/isolate-definitions.json','locator':'RegulatoryRequirement','support':'Existing normative information-object definition motivates source and jurisdiction links.','limit':'Local design inference requiring author review; not new external legal evidence.'}]
write('sources.json',{'accessed':'2026-10-10 Asia/Tehran','sources':sources})
cards=[]
for name,a,b,src,loc in RELS:
 family='event participant/context' if name.startswith(('logistics','procurement')) else 'situation context' if name.startswith('stockout') else 'information source/aboutness' if name.startswith('requirement') else 'disposition realization' if name.startswith('capability') else 'digital-to-physical activity support'
 cards.append({'property':name,'source':a,'target':b,'semantic_family_proposal':family,'source_id':src,'locator':loc,'preferred_action':'Retain as a typed proposal; decide Event/Situation and information-relation representation before choosing a stereotype.','not_justified':'Do not assign material without an identified mediating relator; do not assign mediation merely because two typed nodes are related.','universal_bounds_proposal':'0..* both ends provisionally; no uniqueness/total-participation premise is established.','admission_bound':'At least one declared target only when the bounded profile is selected.','important_limit':'Facility does not distinguish origin/destination/storage role.' if name=='logisticsFacility' else 'Organization role is a procurement context, not proof of buyer/seller authority.' if name=='procurementOrganization' else 'No fixed duration, national shortage or substitution conclusion follows.' if name.startswith('stockout') else 'Neither source presence nor jurisdiction proves applicability/compliance.' if name.startswith('requirement') else 'Realization/support does not by itself prove success, sufficiency or causal effect.','native_stereotype':'PENDING_AUTHOR_AND_REPRESENTATION_REVIEW','accepted':False})
write('relation-decision-cards.json',{'cards':cards,'scope':'Ten explicit design decisions, not ten accepted formal relationships.'})
cores={'RM':['RiskAssessmentActivity','RiskTreatmentActivity','RiskTreatmentPlan','RiskReviewActivity'],'PV':['AdverseEventReportingActivity','PharmacovigilanceRequirement','PostMarketSurveillanceActivity','SignalAssessmentActivity'],'BA':['BusinessArchitectureView','ServiceOfferingSpecification','EnterpriseCapability','PartnerOrganizationRole','StrategicPartnershipAgreement'],'DS':['DigitalInformationSystemComponent','SystemDeploymentActivity']}
goals={'RM':'ارزیابی، برنامهٔ رسیدگی و بازبینی ریسک کیفیت و تداوم عرضهٔ دارو','PV':'پیوند شاهد ایمنی، سیگنال و نتیجهٔ ارزیابیِ قابل‌ردیابی','BA':'توصیف قابلیت و خدمت دارویی و تعهدات همکاری در نمای تحلیلی','DS':'توصیف جزء سامانه، استقرار و منشأ تولید یا تبدیل دادهٔ دارویی'}
gains={'RM':'ضدنمونه تأیید می‌کند وجود برنامه به معنی اجرای اقدام نیست؛ شمار اتصال‌های هسته در این اجرا تغییر نکرد.','PV':'سه شاهد واقعی PRAC با نتایج متفاوت و تفکیک استخراج/تفسیر افزوده شد؛ هیچ علت یا رخداد بالینی ساخته نشد.','BA':'تحقق قابلیت در لجستیک اضافه شد؛ برون‌سپاری عادی بدون مشارکت راهبردی و نقش شریک آزموده شد.','DS':'مسیر رکورد→تبدیل داده→لجستیک افزوده شد؛ فعالیت دیجیتال با فعالیت فیزیکی یکی نیست.'}
gaps={'RM':'شاهد واقعی ارزیابی/بازبینی، معنای نتیجه، اثربخشی اقدام و پذیرش مرز ریسک دارویی','PV':'مدل گروه مواد، رخداد/زمان ارزیابی واقعی، ICSR، تعهدات نسخه‌دار و پذیرش هویت محتوا','BA':'قرارداد واقعی، تفکیک تعهد/سند/رابطه، مالکیت قابلیت و پذیرش حد خدمت','DS':'شاهد واقعی استقرار/عامل، مدیریت نسخه، تفویض مسئولیت و پذیرش نگاشت PROV'}
dossier=json.loads((H.parents[2]/'research/w4/minimum-viable-domains-2026-10-09/domain-dossier.json').read_text())
modules=[]
for m in dossier['modules']:
 k=m['id'];core=cores[k];before=topo['prior_experiment']['adjacency'];after=topo['new_experiment']['adjacency']
 modules.append({'id':k,'name':m['name'],'goal_fa':goals[k],'proposed_core_classes':core,'core_count':len(core),'imports_are_not_counted_as_new_owned_classes':True,'core_isolates_before':[x for x in core if not before[x]],'core_isolates_after':[x for x in core if not after[x]],'external_neighbors_before':len(set().union(*(set(before[x]) for x in core))-set(core)),'external_neighbors_after':len(set().union(*(set(after[x]) for x in core))-set(core)),'gain_fa':gains[k],'remaining_fa':gaps[k],'recommendation':'RETAIN_FOR_MINIMUM_VIABLE_REVIEW','scientifically_accepted':False,'removal_or_transfer_decided':False})
write('domain-coherence.json',{'modules':modules,'interpretation':'Zero core isolates was already true in the prior four-domain experiment. New evidence strengthens functional boundaries; it does not show a new connectivity gain for every domain. Core counts are proposed ownership counts, not a final all-domain inventory.','quality_judgement':'BOUNDED_FUNCTIONAL_EVIDENCE_IMPROVED; FULL_SEMANTIC_COHERENCE_NOT_ESTABLISHED'})
decisions=[
 {'id':'DC-01','topic_fa':'حد مأموریت چهار دامنه','recommendation_fa':'فعلاً هر چهار دامنه در طراحی حداقلی حفظ شوند؛ RM محدود به کیفیت/تداوم عرضه، PV به شواهد ایمنی، BA به قابلیت/خدمت/تعهد، DS به استقرار/منشأ داده.','owner':'Araz scientific review','status':'READY_FOR_REVIEW_NOT_ACCEPTED'},
 {'id':'DC-02','topic_fa':'چهار منزوی باقیمانده','recommendation_fa':'هشت رابطهٔ زمینه‌ای برای چهار مفهوم و دو رابط لجستیکی بررسی شوند؛ رفع انزوا دلیل کافی برای پذیرش نیست.','owner':'Araz scientific review','status':'BOUNDED_TESTS_READY'},
 {'id':'DC-03','topic_fa':'قرارداد برون‌سپاری و مشارکت راهبردی','recommendation_fa':'قرارداد عادی نقش PartnerOrganizationRole یا StrategicPartnershipAgreement ایجاد نکند؛ مدل عمومی تعهد/توافق پیش از تعمیم تکمیل شود.','owner':'Araz scientific review','status':'COUNTERMODEL_READY'},
 {'id':'DC-04','topic_fa':'گروه مواد در سیگنال ایمنی','recommendation_fa':'گروه Progestogens به یک PharmaceuticalSubstance فروکاسته نشود؛ مدل مجموعه و عضویت منبع‌دار طراحی شود.','owner':'assistant design then Araz review','status':'GAP_IDENTIFIED'},
 {'id':'DC-05','topic_fa':'اعتبارسنجی معنایی و انتشار','recommendation_fa':'stereotype و کران روابط، C، PROV، هویت محتوا و آشکارسازها جدا تعیین تکلیف شوند؛ PR ادغام نشود.','owner':'assistant prepares evidence; Araz adjudicates','status':'OPEN'}]
write('decision-dossier.json',{'decisions':decisions,'execution_owner':'assistant','user_role':'Review concrete scientific alternatives; no need to perform the executable research work.','no_new_approval_inferred':True})
now=datetime.now(ZoneInfo('Asia/Tehran')).isoformat()
summary={'created_at':now,'prior_head':repo['prior_head'],'status':'COHERENCE_EXPERIMENT_TESTED_NOT_ACCEPTED','original_baseline_isolates':13,'prior_experimental_isolates':4,'new_experimental_isolates':0,'prior_experimental_components':5,'new_experimental_components':1,'named_classes':141,'native_class_records_including_datatypes':147,'new_classes':0,'new_relations':10,'native_elements':686,'unclassified_relations_before':79,'unclassified_relations_after':89,'admission_pass':t['admission_pass'],'admission_total':t['admission_total'],'query_pass':t['query_pass'],'query_total':t['query_total'],'reasoner_pass':t['reasoner_pass'],'reasoner_total':t['reasoner_total'],'PRAC_records':3,'PRAC_claims':pv['claims'],'pv_pass':pv['pass'],'pv_total':pv['total'],'regression_pass':reg['pass'],'regression_total':reg['total'],'native_guard_pass':native['refusal_pass'],'native_guard_total':native['refusal_total'],'all_23_tasks_retained':True,'issues_open':repo['open'],'issues_closed':repo['closed'],'issues_closed_this_run':0,'gate_progress':'2/5 = 40% unchanged','G3_progress':'2/7 = 28.6% unchanged','native_full_detector_runs':'0/20','baseline_unchanged':True,'scientific_acceptance':False,'PR305_draft':True,'four_domain_disposition':'HOLD'}
write('summary.json',summary)
checkpoint=json.loads((PREV/'continuation-checkpoint.json').read_text());checkpoint.update(title='CM-PharmE v2.1 — four-domain coherence and isolate experiment',date=now,previous_checkpoint='../2.1.0-alpha.1-reporting-context-lab/continuation-checkpoint.json',prior_development_head=repo['prior_head'],summary=summary)
updates={'N03':('چهار مأموریت، هستهٔ پیشنهادی و حدود مالکیت بازنویسی و کمی‌سازی شد','مالکیت جامع همهٔ دامنه‌ها و پذیرش علمی'), 'N05':('هر چهار دامنه حفظ‌اند؛ PV با شاهد واقعی، BA و DS با مسیر لجستیک و ضدنمونه تقویت شدند','داوری پروندهٔ پنج تصمیم و شواهد تجربی RM/BA/DS'), 'N08':('در کپی جدید منزوی‌ها ۴→۰ و مؤلفه‌ها ۵→۱؛ پایه دست‌نخورده است','پذیرش معنای روابط؛ صفر منزوی صرفاً نتیجهٔ ساختاری است'), 'N09':('سناریوهای منزوی‌ها، لجستیک، برون‌سپاری و سه نتیجهٔ واقعی PRAC اضافه شد','گروه مواد، نمونه‌های واقعی سایر دامنه‌ها و پوشش جامع'), 'P3':('پنج تصمیم مشخص با بهترین پیشنهاد و مالک داوری ثبت شد','تصمیم دربارهٔ ۱۰ رابطهٔ تازه و پیشنهادهای علمی قبلی'), 'P4':('ده رابطه در کپی native و OWL با قراردادهای SHACL پیاده شد','تصویب و ادغام هماهنگ؛ قراردادهای داده عین کران‌های عمومی نیستند'), 'P5d':('۲۰ سررابطهٔ جدید نوع مشخص و کران آزمایشی دارند','۱۱ نوع و ۶۶ کران قبلی، ۱۴ تخصص و stereotype روابط؛ مجهول‌ها حذف نشده‌اند'), 'P6a':('۳۲ آزمون قرارداد، ۹ پرس‌وجو و ۸ انتظار منطقی موفق','پوشش متوازن سناریوهای باقی‌مانده'), 'P6b':('دو ضدمدلِ کلاس عمداً تهی با معیار دقیق جدا از سازگاری schema ارزیابی شد؛ شکست اولیه محفوظ','C و تبدیل PROV و اصلاح‌های معنایی مصوب'), 'P6c':('سه ردیف واقعی PRAC و ۱۱ کنترل؛ مرز راهنمای قدیمی و تغییر مقررات ثبت شد','دادهٔ عملیاتی ESMP، ارزیابی واقعی RM، قرارداد BA و رفع CI/#307'), 'P6d':('۱۳۰ رگرسیون، گراف ترکیبی، دادهٔ قدیمی و ۱۰ کنترل نگهبان native موفق','۲۰ آشکارساز، اعتبارسنجی کامل UFO/OWL2 DL و مرور انسانی')}
for task in checkpoint['tasks']:
 if task['id'] in updates:task['current_extension'],task['remaining_fa']=updates[task['id']];task['status']='BOUNDED_EVIDENCE_READY_NOT_ACCEPTED'
checkpoint['next_steps_in_order']=['Design source-qualified substance-group membership for PV without inventing a product/brand or treating a group as a single substance.','Obtain independent real RM review, BA agreement and DS deployment witnesses; preserve documentary versus operational evidence.','Prepare relation-by-relation stereotype/cardinality alternatives for the ten new proposals alongside the earlier C/PROV/RG-07 queue.','Continue ESMP action evidence and establishment/approval source contracts, resolve CI and #307.','After explicit scientific adjudication, integrate native/OWL/SHACL and run the full detector suite; finish human G3 review, then article/Wiki/Pages, diagrams and release.']
checkpoint['remaining_full_candidate_blockers'].update({'new_experimental_isolates':0,'isolate_status':'structurally resolved only in this separate experimental copy; acceptance pending','new_unclassified_relations':10,'null_relation_stereotypes':89,'note':'Overlapping inventories, not independent defect count; null-relation count updated to the new coherence experiment. Other prior semantic/adapter blockers remain.'})
write('continuation-checkpoint.json',checkpoint)
lines=['# وضعیت تمام کارها — انسجام چهار دامنه','','در G3 هستیم. کار اجرایی با دستیار است؛ داوری علمی با آراز. خروج/انتقال چهار دامنه معلق است. هیچ‌یک از ۲۳ کار اصلی کاملاً بسته نشده است.','','| شناسه | کار | انجام‌شده | باقی‌مانده |','|---|---|---|---|']
for task in checkpoint['tasks']:lines.append('| '+' | '.join([task['id'],task['task_fa'],task.get('current_extension','کار قبلی محفوظ؛ پذیرش باز'),task.get('remaining_fa',task['deliverable_fa'])])+' |')
lines+=['','## درصدهای قابل تفسیر','','- رفع ساختاری چهار منزوی باقی‌مانده در کپی آزمایشی: ۴/۴ = ۱۰۰٪؛ پذیرش علمی روابط: هنوز صفر.','- نسبت کاهش منزوی‌های آزمایش نسبت به پایه: از ۹/۱۳ = ۶۹٫۲٪ به ۱۳/۱۳ = ۱۰۰٪؛ افزایش ۳۰٫۸ واحد درصد در این شاخص ساختاری.','- دروازه‌های تاریخی ۲/۵ = ۴۰٪؛ بسته‌های اصلی G3 برابر ۲/۷ = ۲۸٫۶٪؛ هر دو بدون تغییر.','- اجرای معتبر ۲۰ آشکارساز روی کل candidate: ۰/۲۰. درصد کلی وزنی پروژه تعریف نشده است.','','## تمام ایشوهای باز','',f"{repo['open']} باز و {repo['closed']} بسته؛ صفر ایشو در این اجرا بسته شد.",'','| ایشو | عنوان |','|---|---|']
lines += [f"| [#{x['number']}]({x['url']}) | {x['title']} |" for x in repo['issues']]
lines+=['','## گام بعدی','']+[str(i)+'. '+x for i,x in enumerate(checkpoint['next_steps_in_order'],1)]
(H/'work-status-fa.md').write_text('\n'.join(lines)+'\n')
report=['# چهار دامنه و منزوی‌ها: چه چیزی حل شد و چه چیزی باز است؟','','تصمیم معتبر کاربر همچنان تعلیق خروج/انتقال هر چهار دامنه است. پیشنهاد دستیار حفظ موقت آنها با مأموریت حداقلی مشخص است. کار اجرایی و تهیهٔ شواهد بر عهدهٔ دستیار باقی می‌ماند؛ آراز لازم نیست پژوهش و آزمون را از ابتدا انجام دهد. نقش آراز داوری پروندهٔ تصمیم مشخص است.','','## مقایسهٔ نسخه‌ها','','| شاخص | پایهٔ قبلی | آزمایش پیشین | آزمایش این اجرا |','|---|---:|---:|---:|','| مفهوم نام‌دار بدون datatype | ۱۳۸ | ۱۴۱ | ۱۴۱ |','| رابطهٔ دوتایی | ۸۶ | ۱۲۵ | ۱۳۵ |','| مفهوم منزوی | ۱۳ | ۴ | صفر |','| مؤلفهٔ متصل | ۱۴ | ۵ | ۱ |','| رابطه بدون stereotype | ۴۰ | ۷۹ | ۸۹ |','','پایه در اینجا همان `g3-p4a-supply-capacity` و آزمایش پیشین `four-domain-refinement` است. این اعداد دربارهٔ یک نسخهٔ پذیرفته‌شدهٔ انتشار نیستند. چهار منزوی باقیمانده متعلق به خود چهار دامنه نبودند. در هسته‌های پیشنهادی چهار دامنه، پیش از این اجرا هم مفهوم منزوی نداشتیم. افزایش اتصال را نباید به معنی کامل‌بودن یا انسجام معنایی هر چهار دامنه تفسیر کرد.','','## چهار مفهوم باقی‌مانده','','| مفهوم | دامنهٔ قبلی | روابط پیشنهادی تازه |','|---|---|---|','| DistributionLogisticsActivity | Supply Operations | محصول و تأسیسات لجستیک |','| ProcurementActivity | Supply Resilience | محصول و سازمان تدارک |','| StockoutSituation | Supply Resilience | محصول و تأسیسات مواجه با اتمام موجودی |','| RegulatoryRequirement | Regulatory Policy | رکورد منبع و قلمرو مقرراتی |','','دو رابطهٔ دیگر، تحقق قابلیت در لجستیک و پشتیبانی تبدیل داده از لجستیک است. هیچ کلاس جدیدی اضافه نشد. همهٔ عناصر غیرPackage مدل پیشین حفظ شدند؛ ۳۰ عنصر جدید شامل ده رابطه و بیست سررابطه اضافه شد. کران 0..* آزمایشی است و stereotype این روابط هنوز تعیین نشده است. کاهش منزوی‌ها در برابر ده تصمیم معنایی تازه باید سنجیده شود.','','## وضعیت هر دامنه','','| دامنه | هستهٔ پیشنهادی | هدف | پیشرفت این اجرا | باقی‌مانده |','|---|---:|---|---|---|']
for m in modules:report.append('| '+' | '.join([m['name'],str(m['core_count']),m['goal_fa'],m['gain_fa'],m['remaining_fa']])+' |')
report+=['','هسته‌ها به‌ترتیب ۴، ۴، ۵ و ۲ کلاس پیشنهادی دارند. Assertion، SourceRecord، Organization، محصول، تأسیسات و ProvenanceActivity رابط‌های مشترک‌اند؛ آنها را به‌عنوان کلاس تازهٔ متعلق به هر دامنه دوباره نشمرده‌ایم. کم‌بودن کلاس‌ها به خودی خود ضعف نیست، همان‌طور که داشتن مسیر در گراف اثبات کفایت نیست.','','## آزمون و شاهد','','- ۳۲/۳۲ آزمون قرارداد، ۹/۹ پرس‌وجو، ۸/۸ انتظار منطقی و ۱۳۰/۱۳۰ رگرسیون موفق.','- سه ردیف واقعی PRAC به ۱۷ ادعای استخراج‌شده یا تفسیرشده تبدیل شد؛ ۱۱/۱۱ کنترل موفق. پروژستوژن‌ها به یک مادهٔ منفرد فروکاسته نشدند؛ مدل گروه هنوز باز است.','- گراف ترکیبی با ۲۸۷۸ triple دادهٔ مثبت و مدل توسعه‌یافته سازگار است و کلاس نام‌دار ناممکن ندارد. نمونهٔ تاریخی ۷۶۸ ردیفی نیز بازآزمایی شد.','- schema/parser رسمی و نگهبان round-trip اجرا شد؛ ۶۸۶ عنصر و ۱۰/۱۰ آزمون رد تغییر ناخواسته. parser همچنان مقادیر نامعلوم boolean را پیش‌فرض می‌کند؛ نگهبان با رجوع به ورودی اصلی آن را آشکار و اصلاح می‌کند.','- دو ضدمدل عمداً کلاس اجرا/مشارکت را تهی می‌کنند. انتظار اولیه اشتباهاً نبود هر کلاس ناممکن را در آنها الزامی می‌کرد؛ نتیجهٔ اولیه ۶/۸ محفوظ است. معیار اصلاح‌شده سازگاری مدل و دقیقاً همان کلاس‌های عمداً تهی را بررسی می‌کند. این استثنا روی آزمون schema اعمال نشده است.','','## حدود علمی','','نمای native حاضر شامل ده رابطهٔ افزوده به مدل اصلاح‌شده است؛ همهٔ قراردادهای اطلاعاتی و PROV آزمایش‌های بعدی را به native منتقل نکرده‌ایم. هم‌ارزی کامل سه نمایش ادعا نمی‌شود. ۱۱ سررابطهٔ بدون نوع، ۶۶ کران نامعلوم و ۱۴ سررابطهٔ تخصصی قبلی باقی‌اند. C با سابقهٔ ۸۸/۸۹، نگاشت PROV، ۲۰ آشکارساز و داوری انسانی هنوز بازند.','','شاهد PRAC یک سند واقعی تصمیم است؛ بیمار واقعی، پروندهٔ ICSR و اجرای واقعی توصیه‌ها در آن نمونه‌سازی نشده است. BA و DS تازه مصنوعی‌اند و از GDP برای طراحی استفاده می‌کنند. منبع WHO دربارهٔ stockout، چارچوب پیشنهادی یک گزارش جلسه است؛ تعریف جهان‌شمول یا معیار کامل stockout از آن ادعا نشده است. صفحهٔ جاری EMA نیز تغییر مقررات 2025/1466 را یادآور می‌شود؛ GVP IX قدیمی به‌تنهایی مبنای تکلیف قانونی فعلی نیست.','','## تصمیم‌های آمادهٔ بررسی','']
for d in decisions:report += [f"- **{d['id']} — {d['topic_fa']}**: {d['recommendation_fa']}"]
report+=['','گام بعدی قابل اجرا: مدل منبع‌دار گروه مواد برای PV، سپس شاهد واقعی ارزیابی ریسک/قرارداد/استقرار و تحلیل stereotype و کران روابط. تصمیم چهار دامنه در انتظار کار اجرایی شما نیست. هیچ تصمیم علمی از دستور عمومی ادامه‌دادن استنباط نشده است.','','تمام ۲۳ کار و ۳۰ ایشوی باز در `work-status-fa.md` و نقطهٔ ادامه در `continuation-checkpoint.json` حفظ شده‌اند. PR305 پیش‌نویس می‌ماند.','']
(H/'decision-report-fa.md').write_text('\n'.join(report))
(H/'README.md').write_text('''# Four-domain coherence and isolate experiment

This is a separate additive proposal. Four-domain removal/transfer stays on hold. No author acceptance, merge or full native/UFO validation is claimed.

Run `run_lab.py`, `run_pv.py`, then `run_regression.py`, then the existing `../2.1.0-alpha.1-native-fidelity-audit/check_native_fidelity.cjs` with the new native JSON, installed OntoUML node_modules and native-results.json as arguments, then `finalize.py`. Use PYTHONDONTWRITEBYTECODE=1, the preceding labs' Python environment (rdflib 7.6.0, pyshacl 0.30.1, owlready2 0.49), Java 17 and the native runtime versions recorded in native-results.json. Earlier sibling labs are runtime dependencies. Do not import their build scripts because they write artifacts.

run_pv.py downloads the PDF only if its manifest is absent. Extraction rows are manually transcribed from the primary source; replay validates the graph and queries, not an independent extraction. The PDF itself is not archived. Generated blank nodes are not byte-stable. The manifest hashes delivered artifacts, excluding itself.

The topology now has zero isolates in a separate experimental copy. Ten new relations still have pending stereotypes and provisional optional bounds. The native projection adds only those relations to the previous refinement; it does not silently integrate every subsequent information/PROV proposal.

Two bounded countermodels deliberately force particular classes empty, so their expected unsatisfiable named classes are explicit. The unmodified combined schema must still have none. Initial over-strict test results are retained.

See the Persian decision report, complete 23-task status, source register, domain-coherence.json, decision-dossier.json and machine-readable results.
''')
write('runtime.json',{'python_environment_from':str(PREV.name)+'/runtime.json','native_runtime_from':'native-results.json','date':now,'reasoner':'Direct HermiT with prior explicit two-declaration PROV projection','full_OWL2_DL_profile_check':False})
files=[p for p in H.rglob('*') if p.is_file() and p.name!='file-manifest.json' and '__pycache__' not in p.parts]
write('file-manifest.json',{'self_excluded':True,'files':[{'path':str(p.relative_to(H)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(files)]})
print(json.dumps({'summary':summary,'files':len(files)+1},ensure_ascii=False))
