BEGIN TRANSACTION;
CREATE TABLE alias(relator_id TEXT REFERENCES relator(id), property TEXT NOT NULL, entity_id TEXT REFERENCES entity(id), PRIMARY KEY(relator_id,property,entity_id));
CREATE TABLE allowed_kind(profile TEXT, slot TEXT, identity_kind TEXT, role TEXT, PRIMARY KEY(profile,slot,identity_kind));
INSERT INTO "allowed_kind" VALUES('FacilityOperation','operator','Organization','OperatingOrganizationRole');
INSERT INTO "allowed_kind" VALUES('FacilityOperation','facility','Facility','OperatedFacilityRole');
INSERT INTO "allowed_kind" VALUES('EstablishmentRegistration','authority','Organization','RegisteringAuthorityRole');
INSERT INTO "allowed_kind" VALUES('EstablishmentRegistration','subject','Organization','RegisteredOrganizationRole');
INSERT INTO "allowed_kind" VALUES('EstablishmentRegistration','subject','Facility','RegisteredFacilityRole');
INSERT INTO "allowed_kind" VALUES('RegulatoryAuthorization','authority','Organization','AuthorizingAuthorityRole');
INSERT INTO "allowed_kind" VALUES('RegulatoryAuthorization','subject','Organization','AuthorizedOrganizationRole');
INSERT INTO "allowed_kind" VALUES('RegulatoryAuthorization','subject','Facility','AuthorizedFacilityRole');
INSERT INTO "allowed_kind" VALUES('ProductClassificationAssignment','subject','MedicinalProduct','ClassifiedMedicinalProductRole');
INSERT INTO "allowed_kind" VALUES('ProductClassificationAssignment','subject','PharmaceuticalSubstance','ClassifiedPharmaceuticalSubstanceRole');
INSERT INTO "allowed_kind" VALUES('ProductClassificationAssignment','entry','ClassificationEntry','AppliedClassificationEntryRole');
INSERT INTO "allowed_kind" VALUES('MarketListing','presentation','MedicinalProductPresentation','ListedPresentationRole');
INSERT INTO "allowed_kind" VALUES('MarketListing','responsible','Organization','ListingResponsibleOrganizationRole');
INSERT INTO "allowed_kind" VALUES('EvidenceSupport','evidence','SourceRecord','EvidenceSourceRecordRole');
INSERT INTO "allowed_kind" VALUES('EvidenceSupport','evidence','ObservationResult','EvidenceObservationResultRole');
INSERT INTO "allowed_kind" VALUES('EvidenceSupport','claim','Assertion','SupportedAssertionRole');
INSERT INTO "allowed_kind" VALUES('IdentifierAssignment','subject','Organization','IdentifiedOrganizationRole');
INSERT INTO "allowed_kind" VALUES('IdentifierAssignment','subject','Facility','IdentifiedFacilityRole');
INSERT INTO "allowed_kind" VALUES('IdentifierAssignment','subject','MedicinalProduct','IdentifiedMedicinalProductRole');
INSERT INTO "allowed_kind" VALUES('IdentifierAssignment','subject','PharmaceuticalSubstance','IdentifiedPharmaceuticalSubstanceRole');
INSERT INTO "allowed_kind" VALUES('IdentifierAssignment','subject','MedicinalProductPresentation','IdentifiedMedicinalProductPresentationRole');
INSERT INTO "allowed_kind" VALUES('IdentifierAssignment','subject','GeographicFeature','IdentifiedGeographicFeatureRole');
INSERT INTO "allowed_kind" VALUES('IdentifierAssignment','scheme','IdentifierScheme','UsedIdentifierSchemeRole');
INSERT INTO "allowed_kind" VALUES('AlternativeMedicineAssignment','reference','MedicinalProduct','ReferenceProductRole');
INSERT INTO "allowed_kind" VALUES('AlternativeMedicineAssignment','alternative','MedicinalProduct','AlternativeMedicinalProductRole');
INSERT INTO "allowed_kind" VALUES('SupplyDependency','dependent','Organization','DependentOrganizationRole');
INSERT INTO "allowed_kind" VALUES('SupplyDependency','dependent','Facility','DependentFacilityRole');
INSERT INTO "allowed_kind" VALUES('SupplyDependency','dependent','MedicinalProduct','DependentMedicinalProductRole');
INSERT INTO "allowed_kind" VALUES('SupplyDependency','provider','Organization','ProviderOrganizationRole');
INSERT INTO "allowed_kind" VALUES('SupplyDependency','provider','Facility','ProviderFacilityRole');
INSERT INTO "allowed_kind" VALUES('SupplyDependency','provider','MedicinalProduct','ProviderMedicinalProductRole');
INSERT INTO "allowed_kind" VALUES('RegulatoryOversight','authority','Organization','OversightAuthorityRole');
INSERT INTO "allowed_kind" VALUES('RegulatoryOversight','subject','Organization','GovernedOrganizationRole');
INSERT INTO "allowed_kind" VALUES('RegulatoryOversight','subject','Facility','GovernedFacilityRole');
INSERT INTO "allowed_kind" VALUES('StrategicPartnershipAgreement','partner','Organization','PartnerOrganizationRole');
INSERT INTO "allowed_kind" VALUES('ContextualMedicineClassificationAssignment','subject','MedicinalProduct','ClassifiedMedicinalProductRole');
INSERT INTO "allowed_kind" VALUES('ContextualMedicineClassificationAssignment','subject','PharmaceuticalSubstance','ClassifiedPharmaceuticalSubstanceRole');
INSERT INTO "allowed_kind" VALUES('ContextualMedicineClassificationAssignment','entry','ClassificationEntry','AppliedClassificationEntryRole');
CREATE TABLE containment(child TEXT REFERENCES entity(id), parent TEXT REFERENCES entity(id), PRIMARY KEY(child,parent));
CREATE TABLE context(id TEXT PRIMARY KEY, jurisdiction TEXT NOT NULL, scheme_version TEXT NOT NULL);
INSERT INTO "context" VALUES('ctx1','synthetic-J1','v1');
INSERT INTO "context" VALUES('ctx2','synthetic-J2','v2');
CREATE TABLE entity(id TEXT PRIMARY KEY, identity_kind TEXT NOT NULL);
INSERT INTO "entity" VALUES('operator0','Organization');
INSERT INTO "entity" VALUES('facility0','Facility');
CREATE TABLE explicit_role(entity_id TEXT REFERENCES entity(id), role TEXT NOT NULL);
CREATE TABLE participation(relator_id TEXT REFERENCES relator(id), slot TEXT NOT NULL, entity_id TEXT REFERENCES entity(id), PRIMARY KEY(relator_id,slot,entity_id));
INSERT INTO "participation" VALUES('r1','operator','operator0');
INSERT INTO "participation" VALUES('r1','facility','facility0');
CREATE TABLE relator(id TEXT PRIMARY KEY, type TEXT NOT NULL, context_id TEXT REFERENCES context(id), source_id TEXT REFERENCES source(id), valid_from TEXT, valid_to TEXT, lexical_value TEXT);
INSERT INTO "relator" VALUES('r1','FacilityOperation','ctx1','src1','2026-01-01T00:00:00Z','2027-01-01T00:00:00Z',NULL);
CREATE TABLE slot_rule(profile TEXT, slot TEXT, property TEXT, target TEXT, minimum INTEGER, maximum INTEGER, PRIMARY KEY(profile,slot));
INSERT INTO "slot_rule" VALUES('FacilityOperation','operator','operationOrganization','OperatingOrganizationRole',1,NULL);
INSERT INTO "slot_rule" VALUES('FacilityOperation','facility','operationFacility','OperatedFacilityRole',1,1);
INSERT INTO "slot_rule" VALUES('EstablishmentRegistration','authority','registrationAuthority','RegisteringAuthorityRole',1,1);
INSERT INTO "slot_rule" VALUES('EstablishmentRegistration','subject','registrationEntity','RegisteredParty',1,1);
INSERT INTO "slot_rule" VALUES('RegulatoryAuthorization','authority','authorizationAuthority','AuthorizingAuthorityRole',1,1);
INSERT INTO "slot_rule" VALUES('RegulatoryAuthorization','subject','authorizationParty','AuthorizedParty',1,1);
INSERT INTO "slot_rule" VALUES('ProductClassificationAssignment','subject','classificationEntity','ClassifiedEntity',1,1);
INSERT INTO "slot_rule" VALUES('ProductClassificationAssignment','entry','classificationEntry','AppliedClassificationEntryRole',1,1);
INSERT INTO "slot_rule" VALUES('MarketListing','presentation','listingPresentation','ListedPresentationRole',1,1);
INSERT INTO "slot_rule" VALUES('MarketListing','responsible','listingResponsibleOrganization','ListingResponsibleOrganizationRole',1,1);
INSERT INTO "slot_rule" VALUES('EvidenceSupport','evidence','evidenceItem','EvidenceItem',1,1);
INSERT INTO "slot_rule" VALUES('EvidenceSupport','claim','evidenceAssertion','SupportedAssertionRole',1,1);
INSERT INTO "slot_rule" VALUES('IdentifierAssignment','subject','identifierEntity','IdentifiedEntity',1,1);
INSERT INTO "slot_rule" VALUES('IdentifierAssignment','scheme','identifierScheme','UsedIdentifierSchemeRole',1,1);
INSERT INTO "slot_rule" VALUES('AlternativeMedicineAssignment','reference','alternativeForProduct','ReferenceProductRole',1,1);
INSERT INTO "slot_rule" VALUES('AlternativeMedicineAssignment','alternative','alternativeProduct','AlternativeMedicinalProductRole',1,1);
INSERT INTO "slot_rule" VALUES('SupplyDependency','dependent','dependencyDependent','DependentEntity',1,1);
INSERT INTO "slot_rule" VALUES('SupplyDependency','provider','dependencyProvider','ProviderEntity',1,1);
INSERT INTO "slot_rule" VALUES('RegulatoryOversight','authority','oversightAuthorityRole','OversightAuthorityRole',1,1);
INSERT INTO "slot_rule" VALUES('RegulatoryOversight','subject','oversightGovernedEntity','GovernedEntity',1,1);
INSERT INTO "slot_rule" VALUES('StrategicPartnershipAgreement','partner','partnershipParticipant','PartnerOrganizationRole',2,NULL);
INSERT INTO "slot_rule" VALUES('ContextualMedicineClassificationAssignment','subject','classificationEntity','ClassifiedEntity',1,1);
INSERT INTO "slot_rule" VALUES('ContextualMedicineClassificationAssignment','entry','classificationEntry','AppliedClassificationEntryRole',1,1);
CREATE TABLE source(id TEXT PRIMARY KEY, description TEXT NOT NULL);
INSERT INTO "source" VALUES('src1','Synthetic evidence only; no real-world assertion');
CREATE VIEW derived_role AS SELECT DISTINCT p.entity_id,a.role,r.context_id,r.valid_from,r.valid_to
 FROM participation p JOIN relator r ON r.id=p.relator_id JOIN entity e ON e.id=p.entity_id
 JOIN allowed_kind a ON a.profile=r.type AND a.slot=p.slot AND a.identity_kind=e.identity_kind;
COMMIT;
